services:
  base:
    build:
      context: .
      dockerfile: Dockerfile_base
    container_name: rdev_base
    image: rdev:base
    networks:
      - local
  rdev:
    build:
      context: .
      dockerfile: Dockerfile
      additional_contexts:
        rdev:base: service:base
      args:
        RUSER: ${RUSER:?err}
    container_name: rdev
    hostname: rdev
    image: rdev:latest
    networks:
      - local
    ports:
      - "2022:22"
    restart: unless-stopped
    volumes:
      - rdev_home:/home/${RUSER:?err}
      - ./authorized_keys:/home/${RUSER:?err}/.ssh/authorized_keys

networks:
  local:
    external: true

volumes:
  rdev_home:
    external: true
