version: "3.6"

services:
  rdev:
    build:
      context: .
      args:
        mongo_url: "mongodb://rdev:rdev@172.16.16.1:27017/"
    container_name: rdev
    hostname: rdev
    image: 172.16.16.1:5000/rdev:latest
    networks:
    - local
    ports:
      - "2022:22"
      - "8008:8008"
      - "8080:8080"
      - "8888:8888"
    volumes:
      - /opt/rdev:/home/rdev
      - rdev_node_modules:/usr/lib/node_modules

networks:
  local:
    external: true

volumes:
  rdev_node_modules:
    external: true
